---
# tasks file for build_db_image
- name: login into ecr registry
  shell: $(aws ecr get-login --no-include-email --region us-east-1)
  register: pwd

- debug:
    msg: "Password is {{pwd.stdout}}"  

- name: build image
  shell: docker build --no-cache -t  init-db -f Dockerfile.init.db .
  args:
    chdir: ../webapp/