apiVersion: v1
kind: Service
metadata:
  name: csye7374-lb-svc
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn1
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer            
  ports:
  - name: http
    protocol: TCP
    port: 80                 
    targetPort: 5000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 5000          
  selector:
    app: csye7374-webapp